!
! Copyright (C) 2006-2014 Houtan Bastani and Luca Guerrieri
!
!
! This free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! It is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with Dynare.  If not, see <http://www.gnu.org/licenses/>.
!

!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade - Version 2.2 (r1239) - Wed 28 Jun 2006 04:59:55 PM CEST
!
!  Differentiation of aim in forward (tangent) mode: (multi-directional mode)
!   variations  of output variables: cofb
!   with respect to input variables: horig
SUBROUTINE AIM_DV(horig, horigd, neq, nlag, nlead, cofb, cofbd, condn, &
&  uprbnd, info, nbdirs)
  USE DIFFSIZES
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: condn
  INTEGER :: info
  INTEGER :: nbdirs
  INTEGER, INTENT(IN) :: neq
  DOUBLE PRECISION, DIMENSION(neq, neq), INTENT(OUT) :: cofb
  DOUBLE PRECISION, DIMENSION(nbdirsmax, neq, neq), INTENT(OUT) :: cofbd
  DOUBLE PRECISION, DIMENSION(neq, 3*neq), INTENT(IN) :: horig
  DOUBLE PRECISION, DIMENSION(nbdirsmax, neq, 3*neq), INTENT(IN) :: horigd
  INTEGER, INTENT(IN) :: nlag
  INTEGER, INTENT(IN) :: nlead
  DOUBLE PRECISION, INTENT(IN) :: uprbnd
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: a
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: ad
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: asmall
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: asmalld
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: h
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: hd
  INTEGER, DIMENSION(:), ALLOCATABLE :: js
  INTEGER :: ia, iq, nd, nexact, nlarge, nnumeric, qcols, qrows, status
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: q
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: qd
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: w
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: wd
  EXTERNAL NUMERIC_SHIFT_DV, EXACT_SHIFT_DV, BUILD_A_DV, REDUCED_FORM_DV, COPY_W_DV
  qrows = neq
  qcols = neq*2
  iq = 0
  ALLOCATE( h(neq, neq*3), hd(nbdirsmax, neq, neq*3), q(qrows, qcols), qd(nbdirsmax, qrows, qcols), STAT=status)
  IF( status .NE. 0 ) THEN
     WRITE(*,*)
     WRITE(*,*) "***In AIM: Could not allocate memory***"
  END IF
  DO nd=1,nbdirs
    hd(nd, :, :) = horigd(nd, :, :)
  END DO
  qd = 0.D0
  h = horig
  q = 0.0d0


  !
  ! EXACT_SHIFT_DV AND NUMERIC_SHIFT_DV
  !

  CALL EXACT_SHIFT_DV(h, hd, q, qd, iq, qrows, qcols, neq, nexact, nbdirs)
  !CALL writemat_total_3d(qd, nbdirs, qrows,qcols, 'qd_dv.m')
  !CALL writemat_total_3d(hd, nbdirs, neq,3*neq, 'hd_dv.m')


  CALL NUMERIC_SHIFT_DV(h, hd, q, qd, iq, qrows, qcols, neq, condn, nnumeric, nbdirs)

  !CALL writemat_total_3d(qd, nbdirs, qrows,qcols, 'qd_dv.m')
  !CALL writemat_total_3d(hd, nbdirs, neq,3*neq, 'hd_dv.m')


  ALLOCATE( a(qcols, qcols), ad(nbdirsmax,qcols, qcols), js(qcols), STAT=status)
  IF( status .NE. 0 ) THEN
     WRITE(*,*)
     WRITE(*,*) "***In AIM: Could not allocate memory***"
  END IF

  !
  ! BUILD_A_DV
  !
  write(*,*) 'calling build a'

  CALL BUILD_A_DV(h, hd, qcols, neq, a, ad, ia, js, nbdirs)

  ALLOCATE( asmall(ia, ia), asmalld(nbdirsmax,ia, ia), w(ia, ia), wd(nd, ia, ia), STAT=status)
  IF( status .NE. 0 ) THEN
     WRITE(*,*)
     WRITE(*,*) "***In AIM: Could not allocate memory***"
  END IF

  IF (ia .GT. 0) THEN
    DO nd=1,nbdirs
      asmalld(nd, :, :) = ad(nd, js(1:ia), js(1:ia))
    END DO
    asmall = a(js(1:ia), js(1:ia))

	!CALL writemat_total_3d(asmalld, nbdirs, ia, ia, 'ad_dv.m')


    CALL EIGENSYSTEM_DV(asmall, asmalld, ia, uprbnd, w, wd, nlarge, info, nbdirs)
  ELSE
    WRITE(*, *) '**** Problem occurred ****'
    DO nd=1,nbdirs
      wd(nd, :, :) = 0.D0
    END DO
  END IF
  CALL COPY_W_DV(q, qd, qrows, qcols, w, wd, ia, iq, js(1:ia), nbdirs)
  IF (nnumeric + nlarge + nexact .NE. qrows) THEN
    DO nd=1,nbdirs
      cofbd(nd, 1:neq, 1:neq) = 0.D0
    END DO
    RETURN
  ELSE
    CALL REDUCED_FORM_DV(q, qd, qrows, qcols, neq, cofb, cofbd, info, nbdirs)
    !call writemat(cofb,neq,neq,1,neq,1,neq,'cofb_dv.txt')
    IF (info .NE. 0) THEN
       WRITE(*, *) ' **** problems in reduced_form ****'
    END IF
    DEALLOCATE(h, hd, q, qd, a, ad, js, asmall, asmalld, w, wd, STAT=status)
    IF( status .NE. 0 ) THEN
       WRITE(*,*)
       WRITE(*,*) "***In AIM: Could not deallocate memeory***"
    END IF
  END IF
END SUBROUTINE AIM_DV
