!
! Copyright (C) 2006-2014 Houtan Bastani and Luca Guerrieri
!
!
! This free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! It is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with Dynare.  If not, see <http://www.gnu.org/licenses/>.
!

!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade - Version 2.2 (r1239) - Wed 28 Jun 2006 04:59:55 PM CEST
!
!  Differentiation of likelihood in forward (tangent) mode: (multi-directional mode)
!   variations  of output variables: likel
!   with respect to input variables: h
!/********************************************************************
! *
! * SUBROUTINE likelihood():
! *
! * This routine evaluates the likelihood function for a given
! * economic model (as defined by the h matrix below) at a point
! * defined by the parallel arrays psiV, psiL, and the given data on
! * a set of variables determined by the model (contained in the
! * matrix zdata).
! *
! * The model matrix h is written as a function of a parameter
! * vector, psiV.
! *
! *
! ********************************************************************
! * CALLING STRUCTURE:
! *
! * int likelihood( double *likel,
! *		   char **endog, int nEndogVars,
! *		   char **errlist, int nErrVars,
! *	           char **observed, int nObservedVars,
! *		   double *zdata, int TT,
! *		   double *h, int hrows, int hcols,
! *		   int leads, int lags, int neq, int ntrain )
! *
! ********************************************************************/
SUBROUTINE LIKELIHOOD_DV(likel, likeld, endogorig, nendogvarsorig, errlist, &
&  nerrvars, observed, nobservedvars, zdata, tt, h, hd, hrows, hcols, &
&  leads, lags, neq, ntrain, nbdirs)
  USE DIFFSIZES
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: hcols
  INTEGER, INTENT(IN) :: hrows
  DOUBLE PRECISION, DIMENSION(hrows, hcols), INTENT(IN) :: h
  INTEGER, INTENT(IN) :: lags
  INTEGER, INTENT(IN) :: leads
  DOUBLE PRECISION, INTENT(OUT) :: likel
  INTEGER :: nbdirs
  DOUBLE PRECISION, DIMENSION(nbdirsmax, hrows, hcols), INTENT(IN) :: hd
  DOUBLE PRECISION, DIMENSION(nbdirsmax), INTENT(OUT) :: likeld
  INTEGER, INTENT(IN) :: nendogvarsorig
  CHARACTER(len=*), DIMENSION(nendogvarsorig), INTENT(IN) :: endogorig
  INTEGER, INTENT(IN) :: neq
  INTEGER, INTENT(IN) :: nerrvars
  CHARACTER(len=*), DIMENSION(nerrvars), INTENT(IN) :: errlist
  INTEGER, INTENT(IN) :: nobservedvars
  INTEGER, INTENT(IN) :: ntrain
  CHARACTER(len=*), DIMENSION(nobservedvars), INTENT(IN) :: observed
  INTEGER, INTENT(IN) :: tt
  DOUBLE PRECISION, DIMENSION(nobservedvars, tt), INTENT(IN) :: zdata
  CHARACTER(len=20), DIMENSION(:), ALLOCATABLE :: endog
  INTEGER :: nendogvars
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: amat
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: amatd
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: bmat
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: bmatd
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: cofb
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: cofbd
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: q
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: qd
  INTEGER :: diffinvars, err, i, info, nd, status, STRMATCH, zcount
  DOUBLE PRECISION :: condn, uprbnd
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: xi10
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: xi10d
  DOUBLE PRECISION, DIMENSION(:, :), ALLOCATABLE :: z
  DOUBLE PRECISION, DIMENSION(:, :, :), ALLOCATABLE :: zd

  nendogvars = nendogvarsorig

  ALLOCATE( endog(nendogvars), STAT=status)
  IF (status .NE. 0) THEN
    WRITE(*, *)
    WRITE(*, *) '***In Likelihood: Could not allocate memory***'
    info = -1
    err = -1
  END IF
  endog=endogorig


  condn = 0.000000001d0
  uprbnd = 1.0000001d0
  diffinvars = nendogvars - nerrvars

  !
  ! Allocate memory
  !
  status = 0
  ALLOCATE( cofb(neq, neq), cofbd(nbdirsmax, neq, neq), amat(diffinvars, diffinvars), &
            amatd(nbdirsmax, diffinvars, diffinvars), bmat(diffinvars, nerrvars),     &
            bmatd(nbdirsmax, diffinvars, nerrvars), STAT=status )
  IF (status .NE. 0) THEN
    WRITE(*, *)
    WRITE(*, *) '***In Likelihood: Could not allocate memory***'
    info = -1
    err = -1
  END IF




  cofbd = 0.D0
  cofb = 0.0d0
  info = 0

  !!
  !! CALL AIM
  !!
  WRITE(*,*) 'CALLING AIM'
  CALL AIM_DV(h, hd, neq, lags, leads, cofb, cofbd, condn, uprbnd, info, nbdirs)

  call writemat(cofb,neq,neq,1,neq,1,neq,'cofb_dv.m', LEN('cofb_dv.m'))

  !CALL writemat_total_3d(cofbd, nbdirs, neq, neq, 'cofbd_dv.m', LEN('cofbd_dv.m'))

  !!
  !!CALL SPLITMAT
  !!
  CALL SPLITMAT_DV(cofb, cofbd, endog, nendogvars, errlist, nerrvars, amat, amatd, bmat, bmatd, nbdirs)
  DEALLOCATE( cofb, cofbd, STAT=status )
  IF (status .NE. 0) THEN
    WRITE(*, *)
    WRITE(*, *) '***In Likelihood: Could not deallocate memeory for cofb***'
    info = -1
    err = -1
  END IF

  ALLOCATE( q(nendogvars, nendogvars), qd(nbdirsmax, nendogvars, nendogvars), STAT=status )
  IF (status .NE. 0) THEN
    WRITE(*, *)
    WRITE(*, *) '***In Likelihood: Could not allocate memeory for Q***'
    info = -1
    err = -1
  END IF
  DO nd=1,nbdirs
    qd(nd, :, :) = 0.D0
  END DO
  CALL DGEMM_DV('N', 'T', nendogvars, nendogvars, nerrvars, 1.0d0, bmat, bmatd, nendogvars, bmat, bmatd, nendogvars, 0.0d0, &
       q, qd, nendogvars, nbdirs)
  DEALLOCATE( bmat, bmatd, STAT=status )
  IF (status .NE. 0) THEN
    WRITE(*, *)
    WRITE(*, *) '***In Likelihood: Could not deallocate memeory for bmat***'
    info = -1
    err = -1
  END IF

  ALLOCATE( z(nendogvars, nobservedvars), zd(nbdirsmax, nendogvars, nobservedvars), &
            xi10(nendogvars, 1), xi10d(nbdirsmax, nendogvars, 1), STAT=status )
  IF (status .NE. 0) THEN
    WRITE(*, *)
    WRITE(*, *) '***In Likelihood: Could not allocate memeory for Z, xi10***'
    info = -1
    err = -1
  END IF
  DO nd=1,nbdirs
    xi10d(nd, :, :) = 0.D0
    zd(nd, :, :) = 0.D0
  END DO
  xi10(:, :) = 0.0d0
  z(:, :) = 0.0d0
  zcount = 0
  DO i=1,nobservedvars
    DO nd=1,nbdirs
      zd(nd, STRMATCH(observed(i), endog, nendogvars), i) = 0.D0
    END DO
    z(STRMATCH(observed(i), endog, nendogvars), i) = 1.0d0
  END DO


  ! special line for Smets Wouters model
  xi10(strmatch('trend',endog, nendogvars),1) = 1.0d0


  !!
  !! Kalman
  !!
  CALL KALMAN_DV(amat, amatd, nendogvars, z, nobservedvars, zdata, tt, xi10, q, qd, ntrain, likel, likeld, 1, nbdirs)


  DEALLOCATE( amat, amatd, z, q, qd, xi10, xi10d, STAT=status )
  IF (status .NE. 0) THEN
    WRITE(*, *)
    WRITE(*, *) '***In Likelihood: Could not allocate memeory***'
    info = -1
    err = -1
  END IF
END SUBROUTINE LIKELIHOOD_DV
